# Generated by Django 4.2.3 on 2023-07-15 21:05

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gforce', '0002_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
